version: '3.7'
services:
  db:
    image: postgres:13.7-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRESQL_DB=db
      - POSTGRESQL_USER=sashaqa32
      - POSTGRESQL_PASSWORD=F3}Yo{VA
